src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;    

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
    * @ORM\ManyToOne(targetEntity="User")
    * @ORM\JoinColumn(nullable = false)
    */
    private $user;
    
    /**
     * @ORM\OneToMany(targetEntity="Comment", mappedBy="Post")
     */
    protected $comments;
    
    /**
     * @ORM\OneToMany(targetEntity="Video", mappedBy="Post")
     */
    protected $videos;
    
    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @Assert\NotBlank(message="Please, upload image as a jpg file.")
     * @Assert\File(mimeTypes={ "image/jpeg" })
     */
    private $image1;
    
    public function __construct() {
        $this->create_at = new \Datetime();
        /*$this->user = ;*/
    }
    
    public function getImage1()
    {
        return $this->image1;
    }

    public function setImage1($image1)
    {
        $this->image1 = $image1;

        return $this;
    }
    
    public function getVideos() {
        
    }
    
    public function getComments() {
        
    }

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @Assert\File(mimeTypes={ "image/jpeg" })
     */
    private $image2;
    
    public function getImage2()
    {
        return $this->image2;
    }

    public function setImage2($image2)
    {
        $this->image2 = $image2;

        return $this;
    }
    
    /**
     * @ORM\Column(type="string",nullable=true)
     *
     * @Assert\File(mimeTypes={ "image/jpeg" })
     */
    private $image3;
    
    public function getImage3()
    {
        return $this->image3;
    }

    public function setImage3($image3)
    {
        $this->image3 = $image3;

        return $this;
    }
    
    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @Assert\File(mimeTypes={ "image/jpeg" })
     */
    private $image4;
    
    public function getImage4()
    {
        return $this->image4;
    }

    public function setImage4($image4)
    {
        $this->image = $image4;

        return $this;
    }
    
    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('image1', FileType::class, array('label' => 'Image (Jpeg file)'))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\PostType;
use App\Repository\PostRepository;
use App\Entity\Comment;
use App\Form\CommentType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use App\Service\FileUploader;

/**
 * @Route("/post")
 */
class PostController extends Controller
{
    /**
     * @Route("/", name="post_index", methods="GET")
     */
    public function index(PostRepository $postRepository): Response
    {
        return $this->render('post/index.html.twig', ['posts' => $postRepository->findAll()]);
    }

    /**
     * @Route("/new", name="post_new", methods="GET|POST")
     */
    public function new(Request $request, UserInterface $userConnnected , FileUploader $fileUploader ): Response
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $em = $this->getDoctrine()->getManager();    

            $file = $post->getImage1();
            $fileName = $fileUploader->upload($file);
            dump($fileName);
            $post->setImage1($fileName);
            
            $file = $post->getImage2();
            if($file !== null ){
                $fileName = $fileUploader->upload($file);
                $post->setImage2($fileName);
            }
            
            
            $file = $post->getImage3();
            if($file !== null ){
                $fileName = $fileUploader->upload($file);
                $post->setImage3($fileName); 
            }
            
            $file = $post->getImage4(); 
            if($file !== null ){
                $fileName = $fileUploader->upload($file);
                $post->setImage4($fileName);
            }
            
            $post->setUser($userConnnected);
            
            $em->persist($post);
            $em->flush(); 
            
            return $this->redirectToRoute('post_index');
        }
        
        return $this->render('post/new.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
        
    }
    
    public function new_comment(Request $request): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($comment);
            $em->flush();

            return $this->redirectToRoute('comment_index');
        }

        return $this->render('comment/new.html.twig', [
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }
    
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/{id}", name="post_show", methods="GET")
     */
    public function show(Post $post, Comment $comment ): Response
    {
        $comment = $this->Comment->getComment();
        return $this->render('post/show.html.twig', [
            'post' => $post,
            'comment' => $comment
            ]);
    }

    /**
     * @Route("/{id}/edit", name="post_edit", methods="GET|POST")
     */
    public function edit(Request $request, Post $post): Response
    {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('post_edit', ['id' => $post->getId()]);
        }

        return $this->render('post/edit.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }
    
    /**
     * @Route("/{id}", name="post_delete", methods="DELETE")
     */
    public function delete(Request $request, Post $post): Response
    {
        if ($this->isCsrfTokenValid('delete'.$post->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($post);
            $em->flush();
        }

        return $this->redirectToRoute('post_index');
    }
}

templates/post/_delete_form.html.twig
<form method="post" action="{{ path('post_delete', {'id': post.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn">Delete</button>
</form>

templates/post/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Post{% endblock %}

{% block body %}
    <h1>Edit Post</h1>

    {{ include('post/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('post_index') }}">back to list</a>

    {{ include('post/_delete_form.html.twig') }}
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post index{% endblock %}

{% block body %}
    <h1>Post index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Content</th>
                <th>Create_at</th>
                <th>Image1</th>
                <th>Image2</th>
                <th>Image3</th>
                <th>Image4</th>
                <th>platform</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr>
                <td>{{ post.id }}</td>
                <td>{{ post.title }}</td>
                <td>{{ post.content }}</td>
                <td>{{ post.createAt ? post.createAt|date('Y-m-d H:i:s') : '' }}</td>
                <td><img src="../../uploads/image/{{ post.image1 }}"/></td>
                <td><img src="../../uploads/image/{{ post.image2 }}"/></td>
                <td><img src="../../uploads/image/{{ post.image3 }}"/></td>
                <td><img src="../../uploads/image/{{ post.image4 }}"/></td>
                <td>
                    <a href="{{ path('post_show', {'id': post.id}) }}">show</a>
                    <a href="{{ path('post_edit', {'id': post.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('post_new') }}">Create new</a>
{% endblock %}

templates/post/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Post{% endblock %}

{% block body %}
    <h1>Create new Post</h1>

    {{ include('post/_form.html.twig') }}

    <a href="{{ path('post_index') }}">back to list</a>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="../../css/show.css">
{% endblock %}

{% block title %}Post{% endblock %}

{% block body %}
    
    <div id="header">
        <div id="titre">
            {{ post.title }}
        </div>  
    </div>
    
    <div id="block">
        <a href="{{ path('post_index') }}">back to list</a>
        <div>{{ post.createAt ? post.createAt|date('Y-m-d H:i:s') : '' }}</div>    
        <div>{{ post.content }}</div>
        {% if post.image1 %}
            <img src="../../uploads/image/{{ post.image1 }}"/>
        {% endif %}
        {% if post.image2 %}
            <img src="../../uploads/image/{{ post.image2 }}"/>
        {% endif %}
        {% if post.image3 %}
            <img src="../../uploads/image/{{ post.image3 }}"/>
        {% endif %}
        {% if post.image4 %}
            <img src="../../uploads/image/{{ post.image4 }}"/>
        {% endif %}

        <div id="edelete">
            <a href="{{ path('post_edit', {'id': post.id}) }}">edit</a>
            {{ include('post/_delete_form.html.twig') }}
        </div>
    </div>
        
    <div>
        
    <iframe src="https://www.youtube.com/embed/zg1TbAinXUs" allowfullscreen></iframe>   
    <iframe src="//www.dailymotion.com/embed/video/x6s80qr" allowfullscreen></iframe>
    
</div>
               
{% endblock %}